# Generated by Django 5.2 on 2025-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OEEDashboardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("shift", models.CharField(default="Shift 1", max_length=20)),
                ("part_number", models.CharField(max_length=100)),
                (
                    "cycle_time",
                    models.FloatField(help_text="Cycle time for part (in seconds)"),
                ),
                ("plan_production_qty", models.IntegerField()),
                ("rejection_qty", models.IntegerField()),
                ("ok_production", models.IntegerField()),
                ("cycle_off_time", models.FloatField()),
                ("cycle_on_time", models.FloatField()),
                ("convection_temp_1", models.FloatField()),
                ("convection_temp_2", models.FloatField()),
                ("convection_temp_3", models.FloatField()),
                ("cooling_temp_1", models.FloatField()),
                ("cooling_temp_2", models.FloatField()),
                ("total_production", models.IntegerField()),
                ("shift_down_time", models.FloatField()),
                (
                    "remarks_off_time",
                    models.CharField(
                        choices=[
                            ("breakdown", "Breakdown"),
                            ("maintenance", "Maintenance"),
                            ("idle", "Idle"),
                            ("others", "Others"),
                        ],
                        max_length=255,
                    ),
                ),
                ("dft", models.FloatField()),
                ("viscosity", models.FloatField()),
                ("resistivity", models.FloatField()),
            ],
        ),
    ]
