# Generated by Django 5.2 on 2025-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="convection_temp_1",
            field=models.FloatField(help_text="Convection zone 1 Temp"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="convection_temp_2",
            field=models.FloatField(help_text="Convection zone 2 Temp"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="convection_temp_3",
            field=models.FloatField(help_text="Convection zone 3 Temp"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="cooling_temp_1",
            field=models.FloatField(help_text="Cooling zone 1 Temp"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="cooling_temp_2",
            field=models.FloatField(help_text="Cooling zone 2 Temp"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="cycle_off_time",
            field=models.FloatField(help_text="Cycle OFF Time (seconds)"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="cycle_on_time",
            field=models.FloatField(help_text="Cycle ON Time (seconds)"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="dft",
            field=models.FloatField(help_text="DFT"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="part_number",
            field=models.CharField(help_text="Part Number (Recipe)", max_length=100),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="remarks_off_time",
            field=models.CharField(
                choices=[
                    ("breakdown", "Breakdown"),
                    ("maintenance", "Maintenance"),
                    ("idle", "Idle"),
                    ("others", "Others"),
                ],
                help_text="Remarks for OFF Time",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="resistivity",
            field=models.FloatField(help_text="Resistivity"),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="shift_down_time",
            field=models.FloatField(
                editable=False, help_text="Per shift down time in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="total_production",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="viscosity",
            field=models.FloatField(help_text="Viscosity"),
        ),
    ]
