# Generated by Django 4.2.18 on 2025-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0002_alter_oeedashboarddata_convection_temp_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
