# Generated by Django 5.0 on 2025-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0004_remove_oeedashboarddata_dft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="remarks_off_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakdown", "Breakdown"),
                    ("maintenance", "Maintenance"),
                    ("idle", "Idle"),
                    ("others", "Others"),
                ],
                help_text="Remarks for OFF Time",
                max_length=255,
                null=True,
            ),
        ),
    ]
