# Generated by Django 5.0 on 2025-04-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0005_alter_oeedashboarddata_remarks_off_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="remarks_off_time",
            field=models.CharField(
                choices=[
                    ("breakdown", "Breakdown"),
                    ("maintenance", "Maintenance"),
                    ("idle", "Idle"),
                    ("others", "Others"),
                ],
                default=1,
                help_text="Remarks for OFF Time",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
