# Generated by Django 5.0 on 2025-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0006_alter_oeedashboarddata_remarks_off_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="oeedashboarddata",
            name="shift_run_time",
            field=models.FloatField(
                default=1, editable=False, help_text="Per shift run time in seconds"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="remarks_off_time",
            field=models.CharField(help_text="Remarks for OFF Time", max_length=255),
        ),
    ]
