# Generated by Django 5.0 on 2025-04-19 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0007_oeedashboarddata_shift_run_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oeedashboarddata",
            name="shift_run_time",
        ),
    ]
