# Generated by Django 4.2.18 on 2025-04-20 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0008_remove_oeedashboarddata_shift_run_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oeedashboarddata",
            name="shift_down_time",
        ),
    ]
