# Generated by Django 5.0 on 2025-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0009_remove_oeedashboarddata_shift_down_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="cycle_time",
            field=models.FloatField(
                blank=True, help_text="Cycle time for part (in seconds)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="plan_production_qty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="rejection_qty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
