# Generated by Django 5.0 on 2025-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0010_alter_oeedashboarddata_cycle_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="ok_production",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
