# Generated by Django 5.0 on 2025-04-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0011_alter_oeedashboarddata_ok_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="ok_production",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="oeedashboarddata",
            name="total_production",
            field=models.IntegerField(),
        ),
    ]
